### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by bakesteve**
Tests for keyboard events
Tests for scroll
Ignored tests for keyboard initiated scroll
Patch for ev.key till v11 is in
Gulpfile tasks
## Todo

Use react utils not jquery/getdomnode
Phantomjs
Fake some. Jest?
Horizontal scroll on key press
Other keys (tab. Enter.pgup)
Core grid functions (rows, cells, columns etc etc)

### CODE REVIEW

**Comment by andreypopp** [comment]
Why closing it?

**Comment by bakesteve** [comment]
I had meant it to go to the master of our fork

I wasn’t sure how active your repo was going to be now, and we’ve taken a few fairly opinionated approaches to using and extending the grid

I’m happy to open a PR from our master -> yours though and summarise where the core changes are

If you are planning to actively develop on this, great (and it’s a very nice component for a research component!), and we’d be more than happy to contribute

**Comment by andreypopp** [comment]
We definitely going to support and actively developing this component cause it's very important to us.

> I’m happy to open a PR from our master -> yours though and summarise where the core changes are

That would be awesome!

**Comment by bakesteve** [comment]
Great – will do some cleanup and send it through

**Pull request closed without merging**
